<div class="discount-code-box">
    <input type="text" id="discount_code" name="discount_code" placeholder="Enter discount code">
    <button id="apply_discount" class="action apply" type="button">Apply Discount</button>
    <span class="apply-link">
        <a href="javascript:void(0);" id="toggle_discount_code">Apply Discount Code</a>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8" fill="none" width="8" height="8">
            <path d="M2.5 2L4 3.5L5.5 2" stroke="#005eae" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
    </span>
</div>
