<!-- Weather Form -->
<form id="weather-form">
    <label for="city">City *</label>
    <input type="text" id="city" name="city" required>
    <button type="submit">Submit</button>
</form>

<!-- Weather Result -->
<div id="weather-result"></div>

<!-- Weather History -->
<h3>Weather Historical Data <button id="print-btn">Print All</button></h3>
<table id="weather-history">
    <thead>
    <tr>
        <th>City</th>
        <th>Country</th>
        <th>Description</th>
        <th>Temperature (°C)</th>
        <th>Feels Like (°C)</th>
        <th>Pressure (hPa)</th>
        <th>Humidity (%)</th>
        <th>Wind Speed (meter/sec)</th>
        <th>Sunrise (UTC)</th>
        <th>Sunset (UTC)</th>
        <th>Checked On</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('#weather-form').submit(function (event) {
            event.preventDefault();
            var city = $('#city').val();

            $.ajax({
                url: '/signupweather/index/weather',
                type: 'GET',
                data: { city: city },
                success: function (response) {
                    if (response.error) {
                        $('#weather-result').html('<p>' + response.error + '</p>');
                        return;
                    }

                    var weatherHtml = '<ul>' +
                        '<li><b>City:</b> ' + response.name + '</li>' +
                        '<li><b>Country:</b> ' + response.sys.country + '</li>' +
                        '<li><b>Description:</b> ' + response.weather[0].description + '</li>' +
                        '<li><b>Temperature (°C):</b> ' + response.main.temp + '</li>' +
                        '<li><b>Feels Like (°C):</b> ' + response.main.feels_like + '</li>' +
                        '<li><b>Pressure (hPa):</b> ' + response.main.pressure + '</li>' +
                        '<li><b>Humidity (%):</b> ' + response.main.humidity + '</li>' +
                        '<li><b>Wind Speed (meter/sec):</b> ' + response.wind.speed + '</li>' +
                        '<li><b>Sunrise (UTC):</b> ' + new Date(response.sys.sunrise * 1000).toUTCString() + '</li>' +
                        '<li><b>Sunset (UTC):</b> ' + new Date(response.sys.sunset * 1000).toUTCString() + '</li>' +
                        '</ul>';
                    $('#weather-result').html(weatherHtml);
                },
                error: function () {
                    $('#weather-result').html('<p>Error! Please try again.</p>');
                }
            });
        });
    });
</script>
